site_name: Snake Game API Documentation
site_description: Documentation for the Snake Game API with C++ core and Python bindings
site_author: agaddipati
repo_name: agaddipati/snakeAPI
repo_url: https://github.com/agaddipati/snakeAPI
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized

nav:
  - Home: index.md
  - Live Demo:
    - Web Version: https://snake-api-xi.vercel.app
    - API Endpoint: https://snakeapi.onrender.com
  - API Documentation:
    - Overview: api/index.md
    - Endpoints: api/endpoints.md
    - Examples: api/examples.md
  - C++ Core:
    - Overview: cpp/index.md
    - API Reference: cpp/api.md
  - Python API:
    - Overview: python/index.md
    - API Reference: python/api.md
  - Development:
    - Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md 