Snake Game API: core/snake.h File Reference
snake.h File Reference
#include <stdbool.h>
Data Structures
struct Position
struct Game
Macros
#define GRID_WIDTH 20
#define GRID_HEIGHT 20
Enumerations
enum Direction { UP , RIGHT , DOWN , LEFT }
Functions
void * create_game (void)
void destroy_game (void *game)
bool move_snake (void *game)
void change_direction (void *game, Direction new_direction)
bool is_game_over (void *game)
int get_score (void *game)
int get_snake_length (void *game)
void get_snake_positions (void *game, Position *positions)
void get_food_position (void *game, Position *position)
void set_food_position (void *game, int x, int y)
void set_game_speed (void *game, float speed)
float get_game_speed (void *game)
void * create_game_wrapper (void)
void free_game_wrapper (void *game)
bool move_snake_wrapper (void *game)
void change_direction_wrapper (void *game, Direction new_direction)
bool is_game_over_wrapper (void *game)
int get_score_wrapper (void *game)
int get_snake_length_wrapper (void *game)
void get_snake_positions_wrapper (void *game, int *positions)
void get_food_position_wrapper (void *game, int *position)
Macro Definition Documentation
GRID_HEIGHT
#define GRID_HEIGHT 20
Definition at line 8 of file snake.h.
GRID_WIDTH
#define GRID_WIDTH 20
Definition at line 7 of file snake.h.
Enumeration Type Documentation
Direction
enum Direction
Enumerator
UP
RIGHT
DOWN
LEFT
Definition at line 17 of file snake.h.
Function Documentation
change_direction()
void change_direction (void * game, Direction new_direction)
Definition at line 244 of file snake.c.
References change_direction_internal(), and game.
Referenced by test_direction_change().
change_direction_wrapper()
void change_direction_wrapper (void * game, Direction new_direction)
References game.
create_game()
void * create_game (void)
Definition at line 236 of file snake.c.
References create_game_internal().
Referenced by init_suite().
create_game_wrapper()
void * create_game_wrapper (void)
destroy_game()
void destroy_game (void * game)
References game.
Referenced by __attribute__(), and clean_suite().
free_game_wrapper()
void free_game_wrapper (void * game)
References game.
get_food_position()
void get_food_position (void * game, Position * position)
Definition at line 260 of file snake.c.
References game, and get_food_position_internal().
get_food_position_wrapper()
void get_food_position_wrapper (void * game, int * position)
References game.
get_game_speed()
float get_game_speed (void * game)
References game.
get_score()
int get_score (void * game)
Definition at line 250 of file snake.c.
References game, and get_score_internal().
Referenced by test_food_collision(), and test_initial_state().
get_score_wrapper()
int get_score_wrapper (void * game)
References game.
get_snake_length()
int get_snake_length (void * game)
Definition at line 252 of file snake.c.
References game, and get_snake_length_internal().
Referenced by test_food_collision(), and test_initial_state().
get_snake_length_wrapper()
int get_snake_length_wrapper (void * game)
References game.
get_snake_positions()
void get_snake_positions (void * game, Position * positions)
Definition at line 256 of file snake.c.
References game, and get_snake_positions_internal().
Referenced by test_boundaries(), test_direction_change(), test_food_collision(), and test_movement().
get_snake_positions_wrapper()
void get_snake_positions_wrapper (void * game, int * positions)
References game.
is_game_over()
bool is_game_over (void * game)
Definition at line 248 of file snake.c.
References game, and is_game_over_internal().
Referenced by get_game_state_internal(), test_boundaries(), test_game_over(), and test_initial_state().
is_game_over_wrapper()
bool is_game_over_wrapper (void * game)
References game.
move_snake()
bool move_snake (void * game)
Definition at line 242 of file snake.c.
References game, and move_snake_internal().
Referenced by test_boundaries(), test_direction_change(), test_food_collision(), test_game_over(), and test_movement().
move_snake_wrapper()
bool move_snake_wrapper (void * game)
References game.
set_food_position()
void set_food_position (void * game, int x, int y)
Definition at line 264 of file snake.c.
References Game::food, game, Position::x, and Position::y.
Referenced by test_food_collision().
set_game_speed()
void set_game_speed (void * game, float speed)
References game.