Snake Game API: core/snake.c File Reference
snake.c File Reference
#include "snake.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
Macros
#define GRID_WIDTH 20
#define GRID_HEIGHT 20
#define DEBUG_LOG(fmt, ...)
Functions
static void place_food (Game *game)
static bool check_collision (const Game *game, int x, int y)
static Game * create_game_internal (void)
static void free_game_internal (Game *game)
static bool move_snake_internal (Game *game)
static void change_direction_internal (Game *game, Direction new_direction)
static bool is_game_over_internal (Game *game)
static int get_score_internal (Game *game)
static int get_snake_length_internal (Game *game)
static void get_snake_positions_internal (Game *game, Position *positions)
static void get_food_position_internal (Game *game, Position *position)
static Direction get_snake_direction_internal (Game *game)
static void get_game_state_internal (Game *game, int *snake_positions, int *snake_length, int *food_position, int *score, int *direction, bool *is_game_over)
void * create_game (void)
__attribute__ ((visibility("default")))
bool move_snake (void *game)
void change_direction (void *game, Direction new_direction)
bool is_game_over (void *game)
int get_score (void *game)
int get_snake_length (void *game)
void get_snake_positions (void *game, Position *positions)
void get_food_position (void *game, Position *position)
void set_food_position (void *game, int x, int y)
Direction get_snake_direction (void *game)
Macro Definition Documentation
DEBUG_LOG
#define DEBUG_LOG (fmt, ...)
Value:
printf("[DEBUG] " fmt "\n", ##__VA_ARGS__)
Definition at line 11 of file snake.c.
Referenced by change_direction_internal(), check_collision(), create_game_internal(), move_snake_internal(), and place_food().
GRID_HEIGHT
#define GRID_HEIGHT 20
Definition at line 8 of file snake.c.
Referenced by check_collision(), create_game_internal(), place_food(), and test_boundaries().
GRID_WIDTH
#define GRID_WIDTH 20
Definition at line 7 of file snake.c.
Referenced by check_collision(), create_game_internal(), place_food(), and test_boundaries().
Function Documentation
__attribute__()
__attribute__ ((visibility("default")))
Definition at line 238 of file snake.c.
References destroy_game(), free_game_internal(), and game.
change_direction()
void change_direction (void * game, Direction new_direction)
Definition at line 244 of file snake.c.
References change_direction_internal(), and game.
Referenced by test_direction_change().
change_direction_internal()
void change_direction_internal (Game * game, Direction new_direction) static
Definition at line 163 of file snake.c.
References DEBUG_LOG, DOWN, game, LEFT, RIGHT, and UP.
Referenced by change_direction().
check_collision()
bool check_collision (const Game * game, int x, int y) static
Definition at line 32 of file snake.c.
References DEBUG_LOG, game, GRID_HEIGHT, and GRID_WIDTH.
Referenced by move_snake_internal().
create_game()
void * create_game (void)
Definition at line 236 of file snake.c.
References create_game_internal().
Referenced by init_suite().
create_game_internal()
Game * create_game_internal (void) static
Definition at line 50 of file snake.c.
References DEBUG_LOG, game, GRID_HEIGHT, GRID_WIDTH, place_food(), and RIGHT.
Referenced by create_game().
free_game_internal()
void free_game_internal (Game * game) static
Definition at line 80 of file snake.c.
References game.
Referenced by __attribute__().
get_food_position()
void get_food_position (void * game, Position * position)
Definition at line 260 of file snake.c.
References game, and get_food_position_internal().
get_food_position_internal()
void get_food_position_internal (Game * game, Position * position) static
Definition at line 200 of file snake.c.
References game.
Referenced by get_food_position().
get_game_state_internal()
void get_game_state_internal (Game * game, int * snake_positions, int * snake_length, int * food_position, int * score, int * direction, bool * is_game_over) static
Definition at line 211 of file snake.c.
References game, and is_game_over().
get_score()
int get_score (void * game)
Definition at line 250 of file snake.c.
References game, and get_score_internal().
Referenced by test_food_collision(), and test_initial_state().
get_score_internal()
int get_score_internal (Game * game) static
Definition at line 185 of file snake.c.
References game.
Referenced by get_score().
get_snake_direction()
Direction get_snake_direction (void * game)
Definition at line 287 of file snake.c.
References game, and get_snake_direction_internal().
get_snake_direction_internal()
Direction get_snake_direction_internal (Game * game) static
Definition at line 207 of file snake.c.
References game, and RIGHT.
Referenced by get_snake_direction().
get_snake_length()
int get_snake_length (void * game)
Definition at line 252 of file snake.c.
References game, and get_snake_length_internal().
Referenced by test_food_collision(), and test_initial_state().
get_snake_length_internal()
int get_snake_length_internal (Game * game) static
Definition at line 187 of file snake.c.
References game.
Referenced by get_snake_length().
get_snake_positions()
void get_snake_positions (void * game, Position * positions)
Definition at line 256 of file snake.c.
References game, and get_snake_positions_internal().
Referenced by test_boundaries(), test_direction_change(), test_food_collision(), and test_movement().
get_snake_positions_internal()
void get_snake_positions_internal (Game * game, Position * positions) static
Definition at line 191 of file snake.c.
References game.
Referenced by get_snake_positions().
is_game_over()
bool is_game_over (void * game)
Definition at line 248 of file snake.c.
References game, and is_game_over_internal().
Referenced by get_game_state_internal(), test_boundaries(), test_game_over(), and test_initial_state().
is_game_over_internal()
bool is_game_over_internal (Game * game) static
Definition at line 181 of file snake.c.
References game.
Referenced by is_game_over().
move_snake()
bool move_snake (void * game)
Definition at line 242 of file snake.c.
References game, and move_snake_internal().
Referenced by test_boundaries(), test_direction_change(), test_food_collision(), test_game_over(), and test_movement().
move_snake_internal()
bool move_snake_internal (Game * game) static
Definition at line 87 of file snake.c.
References check_collision(), DEBUG_LOG, DOWN, game, LEFT, place_food(), RIGHT, UP, Position::x, and Position::y.
Referenced by move_snake().
place_food()
void place_food (Game * game) static
Definition at line 13 of file snake.c.
References DEBUG_LOG, game, GRID_HEIGHT, and GRID_WIDTH.
Referenced by create_game_internal(), and move_snake_internal().
set_food_position()
void set_food_position (void * game, int x, int y)
Definition at line 264 of file snake.c.
References Game::food, game, Position::x, and Position::y.
Referenced by test_food_collision().