Snake Game API: core/test_snake.c File Reference
test_snake.c File Reference
#include "snake.h"
#include <CUnit/Basic.h>
#include <CUnit/CUnit.h>
Functions
static int init_suite (void)
static int clean_suite (void)
static void test_initial_state (void)
static void test_movement (void)
static void test_direction_change (void)
static void test_food_collision (void)
static void test_game_over (void)
static void test_boundaries (void)
int main (void)
Variables
static Game * game
Function Documentation
clean_suite()
int clean_suite (void) static
Definition at line 14 of file test_snake.c.
References destroy_game(), and game.
Referenced by main().
init_suite()
int init_suite (void) static
Definition at line 9 of file test_snake.c.
References create_game(), and game.
Referenced by main().
main()
int main (void)
Definition at line 110 of file test_snake.c.
References clean_suite(), init_suite(), test_boundaries(), test_direction_change(), test_food_collision(), test_game_over(), test_initial_state(), and test_movement().
test_boundaries()
void test_boundaries (void) static
Definition at line 94 of file test_snake.c.
References game, get_snake_positions(), GRID_HEIGHT, GRID_WIDTH, is_game_over(), move_snake(), Position::x, and Position::y.
Referenced by main().
test_direction_change()
void test_direction_change (void) static
Definition at line 38 of file test_snake.c.
References change_direction(), DOWN, game, get_snake_positions(), LEFT, move_snake(), RIGHT, UP, Position::x, and Position::y.
Referenced by main().
test_food_collision()
void test_food_collision (void) static
Definition at line 55 of file test_snake.c.
References DOWN, game, get_score(), get_snake_length(), get_snake_positions(), LEFT, move_snake(), RIGHT, set_food_position(), UP, Position::x, and Position::y.
Referenced by main().
test_game_over()
void test_game_over (void) static
Definition at line 85 of file test_snake.c.
References game, is_game_over(), and move_snake().
Referenced by main().
test_initial_state()
void test_initial_state (void) static
Definition at line 20 of file test_snake.c.
References game, get_score(), get_snake_length(), and is_game_over().
Referenced by main().
test_movement()
void test_movement (void) static
Definition at line 26 of file test_snake.c.
References game, get_snake_positions(), move_snake(), Position::x, and Position::y.
Referenced by main().
Variable Documentation
game
Game* game static
Definition at line 6 of file test_snake.c.
Referenced by __attribute__(), change_direction(), change_direction_internal(), change_direction_wrapper(), check_collision(), clean_suite(), create_game_internal(), destroy_game(), free_game_internal(), free_game_wrapper(), get_food_position(), get_food_position_internal(), get_food_position_wrapper(), get_game_speed(), get_game_state_internal(), get_score(), get_score_internal(), get_score_wrapper(), get_snake_direction(), get_snake_direction_internal(), get_snake_length(), get_snake_length_internal(), get_snake_length_wrapper(), get_snake_positions(), get_snake_positions_internal(), get_snake_positions_wrapper(), init_suite(), is_game_over(), is_game_over_internal(), is_game_over_wrapper(), move_snake(), move_snake_internal(), move_snake_wrapper(), place_food(), set_food_position(), set_game_speed(), test_boundaries(), test_direction_change(), test_food_collision(), test_game_over(), test_initial_state(), and test_movement().