name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "mkdocs-material>=9.4.0" pdoc3
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz doxygen
      
      - name: Build MkDocs documentation
        run: |
          mkdocs build
          mkdir -p docs/api/python
          pdoc --html --output-dir docs/api/python src/api
      
      - name: Build C++ documentation
        run: |
          mkdir -p docs/c
          cd docs/c
          doxygen Doxyfile
          cd ../..
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: mkdocs
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 